### ISSUE TITLE
font size of \hbox and \text in sub/supscript

### ISSUE THREAD

**Issue by hbghlyj** [ronkok/Temml#35]
**Example**
```
\underbrace{\bigcirc\bigcirc\bigcirc}_{\text{circles }\hbox{circles}}
```
In [LaTeX](https://texlive.net/run?%5Cdocumentclass%7Barticle%7D%0A%5Cusepackage%7Bamsmath%7D%0A%5Cbegin%7Bdocument%7D%0A%5C%5B%5Cunderbrace%7B%5Cbigcirc%5Cbigcirc%5Cbigcirc%7D_%7B%5Ctext%7Bcircles%20%7D%5Chbox%7Bcircles%7D%7D%5C%5D%0A%5Cend%7Bdocument%7D) the font size of `\text` is script size and the font size of `\hbox` is normal size. I assume this is an effect of LaTeX temporarily leaving math mode within the `\hbox`.
![image](https://github.com/ronkok/Temml/assets/53823634/0b790b76-1583-4560-88f5-4643c205a8ce)
In [MathJax](https://www.mathjax.org/#demo) the font size of `\text` is script size and the font size of `\hbox` is normal size.
![image](https://github.com/ronkok/Temml/assets/53823634/8f528861-23f7-4ca5-9784-41c6361c5827)
In Temml, they are of the same size
![image](https://github.com/ronkok/Temml/assets/53823634/f0be4d74-d532-43a1-bc2c-f69fd1fd1c95)

**Comment by ronkok** [comment]
@hbghlyj Thank you for raising these issues. It's always nice to improve the package.

**Comment by ronkok** [comment]
Fixed by release 0.10.18.

**Comment by hbghlyj** [comment]
still have issue with font "STIX Two"
![image](https://github.com/ronkok/Temml/assets/53823634/512c43a9-b91a-4033-a859-0978aed311c2)

**Comment by hbghlyj** [comment]
If we comment out this line
```
mtext {
/*   font-family: STIX2; */
}
```
the sizes will be correct
![image](https://github.com/ronkok/Temml/assets/53823634/ba148db9-9be8-46a9-b104-bbd7763dac5f)

**Comment by ronkok** [comment]
Good catch. The redundant CSS rules for `<mtext>` font family are removed in release v0.10.22.
